[app]

# Note: Replay buffer configurations
# 说明：样本池容量
preload_model_dir = "/data/pre_model/ckpt"
preload_model_id = 47573
preload_model = true
replay_buffer_capacity = 4096

# Note: The ratio of the sample pool capacity that triggers training
# 说明：当样本池中的样本占总容量的比例达到该值时，启动学习
preload_ratio = 1

# Note: When new samples are added to the sample pool, the logic for removing old samples: reverb.selectors.Lifo, reverb.selectors.Fifo
# 说明：当新样本加入样本池时，旧样本的移除逻辑，可选项：reverb.selectors.Lifo, reverb.selectors.Fifo
# 说明：reverb.selectors.Lifo：先进后出(Last In, First Out)
# 说明：reverb.selectors.Fifo：先进先出(First In, First Out)
reverb_remover = "reverb.selectors.Fifo"

# Note: The sampling logic of the Learner from the sample pool: reverb.selectors.Fifo, reverb.selectors.Uniform
# 说明：Learner从样本池中取样的逻辑，可选项：reverb.selectors.Fifo, reverb.selectors.Uniform
# Note: reverb.selectors.Uniform：Samples are selected uniformly at random from the replay buffer, with each sample having an equal probability of being chosen.
# 说明：reverb.selectors.Uniform：从回放缓冲区中随机化均匀地选择样本，每个样本被选中的概率相同。
# Note: reverb.selectors.Fifo：Samples are selected in the order they were added to the replay buffer.
# 说明：reverb.selectors.Fifo：按照先进先出从回放缓冲区中选择样本。
reverb_sampler = "reverb.selectors.Uniform"

# Note: Control strategy for balancing data insertion and sampling in experience replay. Options: SampleToInsertRatio, MinSize
# 说明：控制经验回放库中数据插入与取样的动态平衡策略，可选项：SampleToInsertRatio, MinSize
# Note: How to choose
# 说明：如何选择:
#   Note: - SampleToInsertRatio: Apply when training is faster than sample generation (e.g. GPU training with few envs)
#     说明：适供学习速率快于样本产出速率的场景（如GPU学习、少量环境数目），严格控制每条样本被复用的次数，防止过拟合
#   Note: - MinSize: Apply when sample generation is faster than training (e.g. local CPU training, or many envs)
#     说明：适供样本产出速率快于学习速率的场景（如本地CPU学习、大量环境数目），buffer达到阈值后即可全速学习，不限制复用次数
# Note: reverb_samples_per_insert: Max sampling times per inserted sample (only for SampleToInsertRatio)
# 说明：参数reverb_samples_per_insert: 每插入1条样本允许取样的最大次数（仅SampleToInsertRatio模式生效）
# Note: reverb_error_buffer: Tolerance buffer for ratio constraint, similar to TCP sliding window (only for SampleToInsertRatio)
# 说明：参数reverb_error_buffer: 比例限制的弹性缓冲区间，类似TCP滑动窗口（仅SampleToInsertRatio模式生效）
reverb_rate_limiter = "SampleToInsertRatio"
reverb_samples_per_insert = 8
reverb_error_buffer = 8

# Note: Training batch size limit for Learner
# 说明：Learner学习时样本批处理大小
train_batch_size = 2048

# Note: Model dump frequency (steps)
# 说明：学习间隔多少步产出模型参数文件
dump_model_freq = 50

# Note: The Learner pushes model updates, and the frequency at which Actors fetch the model (in minutes).
# 说明：Learner推送模型参数文件至模型池，以及Actor从模型池获取模型参数文件的频次（单位：分钟）
model_file_sync_per_minutes = 1

# Note: he number of model updates pushed per learner iteration, and the maximum number of updates each actor can fetch at once (cap: 50).
# 说明：Learner每次推送模型参数文件，以及Actor每次获取模型参数文件的数量（上限：50）
modelpool_max_save_model_count = 1

# Note: Whether to turn on the preload model function. If enabled (true), the model specified by preload_model_id will be loaded as the initial model in the preload_model_dir directory; if disabled (false), no preloading will be performed.
# 说明：是否启用预读取模型功能，若启用(true)，将在preload_model_dir目录下读取由preload_model_id指定的模型作为初始模型；若停用(false)，则不进行预读取。

# Note: The relative path of the preloaded model folder (the variable name {agent_name} refers to the agent_algorithm name directory in the code package). It is only effective when preload_model=true. When the preload model function is enabled, you need to build a new ckpt folder under the agent_algorithm name directory in the code package and place the model file (.pkl) there.
# 说明：预读取模型文件夹相对路径(变量名{agent_name}指代码包中agent_算法名目录)，仅在preload_model=true时生效；当启用预读取模型功能时，需要在代码包中agent_算法名目录下新建ckpt文件夹，将模型文件（.pkl）放置此即可。

# Note: The identification ID of the preloaded model (here refers to the number of model training steps). This ID corresponds to the number of training steps recorded in the model file name. It only takes effect when preload_model=true.
# Note: Note that it is forbidden to modify the original model file name, otherwise the model preloading process will fail.
# 说明：预读取模型的标识ID（这里指模型学习步数），该ID对应模型文件名中的学习步数记录。仅在preload_model=true时生效。
# 说明：注意，禁止修改原始模型文件名，否则将导致模型预读取流程失败。

eval_model_dir = "/data/projects/legged_robot_competition_26/ckpt"
eval_model_id = "47673"
